# Generated by Django 4.2.16 on 2024-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('star', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.IntegerField(blank=True, default=1, null=True)),
                ('snsimage', models.ImageField(upload_to='')),
                ('is_sale', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
                ('readText', models.TextField(blank=True, default='a', null=True)),
            ],
        ),
    ]
