# Generated by Django 4.2.16 on 2024-10-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='readText',
        ),
    ]
