# Generated by Django 4.2.16 on 2024-10-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0004_items_created_at_items_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
