# Generated by Django 4.2.16 on 2024-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0005_alter_cartitemmodel_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
