# Generated by Django 4.2.16 on 2024-11-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0006_alter_cartitemmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='Item',
            new_name='item',
        ),
    ]
