# Generated by Django 4.2.16 on 2024-11-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0007_rename_item_cartitemmodel_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='user',
        ),
    ]
