# Generated by Django 4.2.16 on 2024-11-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0009_checkoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='credit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='cvv',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
