# Generated by Django 4.2.16 on 2024-11-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0011_alter_checkoutmodel_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='django_ec.cartmodel'),
        ),
    ]
