# Generated by Django 4.2.16 on 2024-11-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0013_alter_checkoutmodel_cart_purchasedetailmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetailmodel',
            name='item_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
