# Generated by Django 4.2.16 on 2024-11-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0014_purchasedetailmodel_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetailmodel',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedetailmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasedetailmodel',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
