# Generated by Django 4.2.16 on 2024-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0015_alter_purchasedetailmodel_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetailmodel',
            name='item_price_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
