# Generated by Django 4.2.16 on 2024-11-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0017_checkoutmodel_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetailmodel',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
