# Generated by Django 4.2.16 on 2024-11-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0018_purchasedetailmodel_is_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetailmodel',
            name='item_list',
        ),
        migrations.RemoveField(
            model_name='purchasedetailmodel',
            name='item_price_list',
        ),
        migrations.RemoveField(
            model_name='purchasedetailmodel',
            name='total_price',
        ),
    ]
