# Generated by Django 4.2.16 on 2024-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0019_remove_purchasedetailmodel_item_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_code', models.CharField(max_length=100)),
                ('discount_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
