# Generated by Django 4.2.16 on 2024-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ec', '0020_promotioncodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncodemodel',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
